### ISSUE TITLE
Can you please cut a release ? 

### ISSUE THREAD

**Issue by cyrinux** [slingamn/vault-exfiltrate#6]
Hi !
Can you cut a tag/release
Maybe use goreleaser to simplify you the life?
If you can support x86_64 and arm64 at least 😉
Thanks!

**Comment by slingamn** [comment]
https://github.com/slingamn/vault-exfiltrate/releases/tag/v0.1.0 :-)

**Comment by cyrinux** [comment]
Thank you ! Happy new year !
